#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;

int main()
{
    int guess;
    char play;
    srand(time(0));

    do {
        int Randnum = rand() % 100 + 1;
        cout << "!NUMBER GUESSING GAME!" << endl;
        cout << "Guess the random number between 1 to 100 generated by the computer." << endl;

        while (true) {
            cin >> guess;
            if (guess > Randnum) {
                cout << "Your guess is high: " << guess << endl;
            } else if (guess < Randnum) {
                cout << "Your guess is low: " << guess << endl;
            } else {
                cout << "Your guess is right...!" << endl;
                cout << "You win...!" << endl;
                cout << guess << " = " << Randnum << endl;
                break;
            }
        }

        cout << "Do you want to play again? (y/n): ";
        cin >> play;

    } while (play == 'y' || play == 'Y');

    cout << "Thank you for playing...!"<< endl;
    return 0;
}
